spring:
  datasource:
    url: jdbc:postgresql://fintex.ce.com:34532/ce
  redis:
    use-key-prefix: true
    key-prefix: pcs-dev

redis:
  host: localhost.com
  port: 13901

fas-graphql-transport:
  location: https://security-master-service.fintex.com/graphql
