package com.fintex.ce.constant;

/**
 * Caches could be: {@this}_CANADA_ETF {@this}_US_ETF {@this}_STOCKS {@this}_US_STOCKS {@this}_CANADA_STOCKS etc..
 */
public enum CacheNameEntity {
  MANAGEMENT_FEE,
  MER,
  MONTHLY_RETURNS,
  HISTORICAL_NAV_PRICES,
  HISTORICAL_DISTRIBUTIONS,
  EQUITY_COUNTRY_ALLOCATIONS,
  EQUITY_STYLEBOX_ALLOCATION,
  INCOME_FORECAST,
  YIELD,
  MATURITY_ALLOCATION,
  FIXED_INCOME_STYLEBOX_ALLOCATION,
  CLASSIFICATION_ALLOCATION,
  BUSINESS_COUNTRY,
  ASSET_ALLOCATION,
  COUNTRY_EXPOSURE,
  CREDIT_QUALITY,
  EQUITY_SECTOR,
  EQUITY_MARKET_CAPITALIZATION,
  FIXED_INCOME_BOND_SECURITIES,
  TOP_COMMON_HOLDINGS,
  SALES_CHARGE
}
