package com.fintex.ce.domain.model.enumeration;

public enum DataType {
  ASSET_ALLOCATION,
  COMMON_HOLDINGS,
  EQUITY_SECTOR,
  EQUITY_COUNTRY_ALLOCATION,
  EQUITY_MARKET_CAP,
  CREDIT_QUALITY,
  MATURITY_ALLOCATION,
  FIXED_INCOME_SECTOR,
  FIXED_INCOME_STYLEBOX,
  EQUITY_STYLEBOX,
  MONTHLY_RETURNS,
  YIELD,
  SALES_CHARGE,
  INCOME_FORECAST,
  MANAGEMENT_FEE,
  AVERAGE_MER,
  COUNTRY_EXPOSURE,
  CLASSIFICATION_ALLOCATION,
  BUSINESS_COUNTRY
}