plugins {
    id 'java-test-fixtures'
}

description = 'Port interfaces (input and output)'

dependencies {
    api project(':domain')
    api libs.jackson.annotations
    api libs.jackson.databind
    api libs.guava
    api libs.commons.lang3

    testFixturesImplementation libs.junit.jupiter.api
    testFixturesImplementation libs.commons.math3
    testFixturesImplementation libs.slf4j.api

    testImplementation libs.junit.jupiter.params
}
