trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  ACR_NAME: crfintexfndservdevcc01
  IMAGE_NAME: calculation-engine-service
  RESOURCE_GROUP: rg-fintex-fndserv-dev-cc-01
  CONTAINER_APP_NAME: calculation-engine-service

stages:
  - stage: BuildAndPush
    displayName: Build & Push Image
    jobs:
      - job: Build
        displayName: Build and Push
        steps:
          - task: DownloadSecureFile@1
            name: GetMavenSettings
            displayName: Get maven settings
            inputs:
              secureFile: 'settings.xml'

          - script: |
              mkdir -p ~/.m2
              cp "$(GetMavenSettings.secureFilePath)" ~/.m2/settings.xml
            displayName: 'Apply Maven settings'

          - task: Maven@4
            displayName: Jib build & push
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              goals: |
                jib:build
              options: >
                -Djib.to.image=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) \
                -Djib.to.auth.username=$(ACR_NAME) \
                -Djib.to.auth.password=$(ACR_PASSWORD)

  - stage: Deploy
    displayName: Deploy to Azure Container Apps
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: '7395443c-24f1-4f3e-8b05-e6cd06a64e0b'  # service connection к подписке Azure
              acrName: $(ACR_NAME)
              resourceGroup: $(RESOURCE_GROUP)
              containerAppName: $(CONTAINER_APP_NAME)
              imageToDeploy: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)'
